[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.119.1",
    "pydantic>=2.12.3",
    "uvicorn>=0.38.0",
]
